spring.application.name=AICodeReviewAssistant-ApiGateway
server.port=8090

server.servlet.context-path=/api-gateway

jwt.secret=At49nAV@B%4P*302@tsk5th1kVNCytW@

//mail
spring.mail.properties.mail.debug=true
spring.mail.host=smtp.zoho.in
spring.mail.port=587
spring.mail.username=manikandan.m@encipherhealth.com
spring.mail.password=pzgAfKPH7vFy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
exception.mail.to=imran.a@encipherhealth.com

constant-coreEngineServiceUrl = "http://localhost:8091/core/"
